### ISSUE TITLE
DSL vs API

### ISSUE THREAD

**Issue by nthsense** [soul-lang/SOUL#10]
Let me know if there's a better forum for this kind of feedback - and consider this an offer to help, if you're open to community involvement.

I'm pretty excited about this project.  As I was perusing the language documentation, I could see where you're borrowing heavily from other languages and also introducing some of your own constructs.  As good as the language itself is, I couldn't help feeling that you might see faster adoption if developers were writing in the languages they already know.  Maybe there's an opportunity for language bindings to be written on top of SOUL?

I could see some potential barriers to that approach - JavaScript has no `int` type, for example - but with the right API, those shortcomings could be worked around.  

As an aside, many JavaScript devs would have no idea why you would use an int vs a float (as just one example) so if spreading audio programming to the masses is one of the project aims, it might be worthwhile to consider some syntactic sugar as part of the recipe.  An API could help guide devs to make the right choices.

Cheers!

**Comment by julianstorer** [comment]
We'd like to reserve the issue tracker for actual bugs/FRs rather than a forum for discussion!

It deserves an answer though, so maybe repost the same question on the JUCE forum https://forum.juce.com/ and I can answer it over there?

**Comment by nthsense** [comment]
Done!  https://forum.juce.com/t/api-vs-dsl/33423

Thanks.
