### ISSUE TITLE
SOUL Language Guide: unused variable audioSum in ExampleGraph

### ISSUE THREAD

**Issue by dstrub18** [soul-lang/SOUL#11]
We studied the documentation and the examples yesterday and found an unused / incorrectly named variable `audioSum` in an example. If we understood the example correctly, it should be named `myOutput` .

`

    graph ExampleGraph
    {
        output stream float audioSum;
        output stream float voiceOut[8];

    let
    {
        voices = SynthesiserVoice[8];   // 8 voices
        delays = Delay[4];              // 4 delays
    }

    connection
    {
        voices[0].audioOut -> delays[0].audioIn;   // 1-to-1 first element of voices array feeds first delay
        voices[1].audioOut -> delays.audioIn;      // 1-to-many second voice feeds all delays
        delays.audioOut    -> myOutput;            // many-to-1 sum of all delay output feeds myOutput
        voices.audioOut    -> voiceOut;            // many-to-many each voice output feeds exactly one voiceOut stream

        voices.audioOut    -> delays.audioIn;      // ERROR - voices has 8 elements, delays has 4 elements
    }
}

`

**Comment by cesaref** [comment]
indeed, that looks wrong. I'll update the documentation

**Comment by cesaref** [comment]
This is now resolved
