### ISSUE TITLE
Missing dependency: soul_utilities

### ISSUE THREAD

**Issue by pauliusuza** [soul-lang/SOUL#14]
Importing soul_venue_audioplayer module inside JUCE fails with error.

Seems there's a missing dependency. Definition here:
https://github.com/soul-lang/SOUL/blob/master/source/modules/soul_venue_audioplayer/soul_venue_audioplayer.h#L32

Used here:
https://github.com/soul-lang/SOUL/blob/master/source/modules/soul_venue_audioplayer/audio_player/soul_AudioPlayer.cpp#L748

Would it be possible for you to publish this?
Thanks

**Comment by julianstorer** [comment]
Yes - we know! It's not an issue, we've just not published all the code yet. 

We're going to work on opening up that lower-level API as one of our next tasks, though still not 100% decided on exactly what form the API will which is why we've not done it yet.
