### ISSUE TITLE
404 links in readme and soul command documentation

### ISSUE THREAD

**Issue by p-jaya** [soul-lang/SOUL#16]
Minor documentation issue.

[README.md](https://github.com/soul-lang/SOUL/blob/master/README.md) and [SOUL_Command.md](https://github.com/soul-lang/SOUL/blob/master/docs/SOUL_Command.md) both reference this dead link:

https://github.com/soul-lang/SOUL-binaries/tree/master/soul_command

I think it perhaps should reference https://github.com/soul-lang/SOUL/releases instead?

If this is correct and you're accepting pull requests I'll send one over.

**Comment by cesaref** [comment]
Yes, good spot. Our documentation has drifted out of date and we'll be correcting this today.

**Comment by cesaref** [comment]
Ok, that should be fixed, and new binaries uploaded
