### ISSUE TITLE
SOULPatchHostDemo not working on macOS

### ISSUE THREAD

**Issue by gwsounddsg** [soul-lang/SOUL#17]
JUCE v5.4.5
macOS v10.15.2

Building and running SOULPatchHostDemo via the Projucer then Xcode isn't working. The GUI states: 

> Can't find the SOUL patch DLL!
You'll need to put the DLL (or a symlink) next to this executable so that it can be loaded. (Or hard-code some app logic to make sure it gets loaded from wherever you want to keep it.)

I searched the root folder SOUL-master and didn't find any DLL files. How do I proceed?

Thanks,
GW

**Comment by cesaref** [comment]
The shared library is distributed as a binary release - you'll want to download the OSX binaries from https://github.com/soul-lang/SOUL/releases/latest and install these alongside the build

**Comment by gwsounddsg** [comment]
Fantastic, thanks for that. 

I think the README should be updated with that info to make it easier for folks to play with the examples.
