### ISSUE TITLE
DebugMessageHandler has wrong documentation

### ISSUE THREAD

**Issue by christophhart** [soul-lang/SOUL#22]
Seems like the docs from the ExternalDataProvider class has been copied over to the DebugMessageHandler class.

https://github.com/soul-lang/SOUL/blob/24ce44f9d2e40b0cea578a1e264bcf26a59a0ba0/source/API/soul_patch/API/soul_patch_Instance.h#L121

**Comment by julianstorer** [comment]
oops! Thanks Christoph, I'll tidy that up
