### ISSUE TITLE
Project/Cmake files to build compiler

### ISSUE THREAD

**Issue by billyquith** [soul-lang/SOUL#37]
Hi! I was wondering if you had any cmake project files to generate a build project? I guess you guys are using Mac for main dev?

Cheers!

**Comment by julianstorer** [comment]
At the moment we've not released 100% of the code that you'd need to do a compiler build yourself - there's still some closed-source bits, so we're expecting people to use our pre-built compiler. (Hoping this will change in the future, lawyers permitting). But yes, when that happens, we'll almost certainly have a cmake build for it.
