### ISSUE TITLE
play --output-devices="" argument won't run if there are spaces in the output device name

### ISSUE THREAD

**Issue by agdsat134** [soul-lang/SOUL#46]
I tried running this command:

`soul play --output-device="Speakers (USB Audio CODEC )" newpatch.soulpatch`

With the latest release but I get the following error:

`Unrecognised command-line argument: newpatch.soulpatch`

After playing around with it a bit, it appears it just doesn't like spaces in the output device name. "Speakers (USB Audio CODEC )" is what is listed in the --list-devices command. I'm using Powershell on Windows 10 Pro x64.

**Comment by cesaref** [comment]
Yes, i've recreated this issue on OSX and am looking for a fix.

**Comment by cesaref** [comment]
I've got a fix which will be included in the next release
