### ISSUE TITLE
Question: Visual editor

### ISSUE THREAD

**Issue by Nauss** [soul-lang/SOUL#48]
Hi,

I'm interested in developing a "Visual Editor" for SOUL but I have a few questions:
- I understood from this [talk](https://www.youtube.com/watch?v=ONN8v4UhNIg) that you are already thinking about some tool to visually edit SOUL code. Is this an on-going project ?
- If not, are you willing to let this part be developed by someone else and be fully open sourced ?

I was thinking about something looking like [Unity shader graphs](https://unity.com/shader-graph) as a modern web app (React, WebAssembly...).

For the context, I'm a software engineer from France and with the current covid situation I happen to have some "free time" (partial unemployment). Being passionate about programming I want to start a side/pet project. One of the main goal driving my choice is creativity. From there I went to music, discovering all the amazing live coding and DSP languages stuff to finally discover SOUL. I do not have an audio background but I professionally develop C++ (particularly for signal processing) and JavaScript (for the UIs).

**Comment by julianstorer** [comment]
Hi - great that you're interested in getting stuck in!

Well yes, we were just about to kick off some work on building this sort of a tool, but that shouldn't be a reason for you to not have a go. Could be that if you beat us to it and do a great job, we could work together on it!

The issue tracker's a bit of an awkward place to discuss stuff like this, but if you want to chat about it on e.g. theaudioprogrammer's discord channel, I'd be happy to share my (very early stage!) thoughts on what this kind of a tool might need to do.

**Comment by Nauss** [comment]
I agree, Discord is a better place to chat about that, I'll reach to you there. Thanks !
