### ISSUE TITLE
Question about web suport

### ISSUE THREAD

**Issue by fedor-rusak** [soul-lang/SOUL#49]
Hello and thank you for such a cool project.

I am interested in music and javascript so I thought that maybe there is source code for playground part of soul.dev web-site.

To play around with UI and to look closer on integration with WebAudio and WebWorkers.

It is considered closed source and priority for near future?

Thank you and have a nice day.

**Comment by julianstorer** [comment]
Glad you like it! No, the website's not open-source, but I'm not sure it'd be much use to see the code anyway. If you want to do your own wasm integrations and know about web-audio then you should be able to see what's going on by just using the command-line soul tool to generate some wasm and look at the result.

The github issue tracker is for BRs/FRs, not for this kind of question - if you want to ask more "how-to" questions about this, maybe try something like the soul channel on https://theaudioprogrammer.com/ discord channel, where I think some other people have also been talking about doing similar stuff with it.

**Comment by objectkit** [comment]
A blessing, @julianstorer.  I tuned in to ask the same question with regard to WASM to see it not only answered but implemented. A test case away from evidence, but cannot deny how impressed I am. This is an amazingly robust and well thought out language release in its own right, and hopefully also for the web, which most definitely needs the Solvency Of Universal Love to bring the heart back to code! Sorry for gushing, just wanted to share the joy and give back some gratitude _/\_

**Comment by cesaref** [comment]
I'll also add that some documentation about how to generate the wasm, and what the generated interface looks like can be found here: https://github.com/soul-lang/SOUL/blob/master/docs/SOUL_WASM.md
