### ISSUE TITLE
jassert in SOULPatchAudioProcessor::injectMIDIMessage

### ISSUE THREAD

**Issue by maxwellpollack** [soul-lang/SOUL#50]
Calling `soul::patch::SOULPatchAudioProcessor::injectMIDIMessage` leads to a `jassert` in `juce::MidiMessageCollector::addMessageToQueue`

https://github.com/juce-framework/JUCE/blob/b8206e3604ebaca64779bf19f1613c373b9adf4f/modules/juce_audio_devices/midi_io/juce_MidiMessageCollector.cpp#L59

because the MIDI message timestamp is set to `0.0`.

https://github.com/soul-lang/SOUL/blob/d62a15e8567de5a7510e2019bd5240de34594905/include/soul/patch/helper_classes/soul_patch_AudioProcessor.h#L382

Should a `double timeStamp` argument be added to `injectMIDIMessage`?

**Comment by julianstorer** [comment]
Thanks - yes, that does look like a simple bug on my part, it should use the current time instead. I'll get a fix pushed to master asap!
