### ISSUE TITLE
Add INSTALL file 

### ISSUE THREAD

**Issue by ycollet** [soul-lang/SOUL#55]
An INSTALL file describing how to compile the command line tool and the JUCE plugin should be added.

**Comment by julianstorer** [comment]
At the moment we've not yet released some of the source code that you'd need to build the command-line tool. When we do then of course we'll publish build instructions for it! :)

**Comment by ycollet** [comment]
Thank ! 
As soon as you release that, I will package soul for Fedora 32 / 33.

**Comment by julianstorer** [comment]
Thanks!
