### ISSUE TITLE
[LICENSE.md](https://github.com/soul-lang/SOUL/blob/master/LICENSE.md) should be changed to text of ISC license

### ISSUE THREAD

**Issue by kryptine** [soul-lang/SOUL#57]
Since all the source code is licensed under the ISC license and this repository contains no binary material, the `LICENSE.md` file in this repository should be changed to include the actual license text so that GitHub detects the right license.

**Comment by julianstorer** [comment]
Well.. we avoided doing that because I think it'd mean we'd trolled over the fact that you can't yet compile something that uses SOUL without also using our binaries, which are not ISC. But I'll have a look and maybe see if I can make the license a bit clearer.
