### ISSUE TITLE
More complete documentation

### ISSUE THREAD

**Issue by m-hilgendorf** [soul-lang/SOUL#6]
Playing around a bit with the playground, the following is currently undocumented: 

- `sin`, `cos`, `tan`
- `asin`, `acos`, `atan`, `atan2`
- `sinh`, `cosh`, `tanh`
- `exp`, `pow`, `sqrt`
- `log`, `log10` (no `log2`?)
- `ceil`, `floor`, `abs`, `fmod`
- `pi`, `twoPi` (any other global constants?)
- `soul::NoteEvents` (only what is seen in the examples?) 
- anything else? 

w.r.t the `<cmath>` equivalents, will those remain in a "global" namespace or will they be a part of the `soul` namespace? 

I understand you're hard at work on the API, but it would be nice to know what the API is so we can help contribute!

**Comment by cesaref** [comment]
That's a good point - we haven't got a sensible list of the supported intrinsics, and what data types are supported. I'll get a complete list included in the language guide. These will remain in the global namespace.

The soul namespace is a set of useful library functions that we found ourselves copying between examples all the time, and it is included by default in the web playground. I'll dig out the code and find an appropriate place to post it.
