### ISSUE TITLE
WASM example

### ISSUE THREAD

**Issue by tristanMatthias** [soul-lang/SOUL#60]
Hey guys! Great project here. Would really love to implement it over at https://synthia.app

I'm a little stuck on how to use the WASM functions. Can you setup an example of how JS can call the functions with the WebAudioContext? (Please forgive my noobiness of WASM)

Thanks!

**Comment by julianstorer** [comment]
Hi - sorry, I only just noticed this issue! Not sure why we missed it, we're normally a lot more on-the-ball than that!

We do have a bit of info about the wasm stuff here:
https://github.com/soul-lang/SOUL/blob/master/docs/SOUL_WASM.md

Some other people have also been tinkering with it, and we were giving them some help over on theaudioprogrammer.com's discord channel:
https://discord.gg/xf7VF3Qw
(hopefully that link will work!) That's probably the best place to find us for quick questions about this kind of thing.

Your site looks awesome! Loving the style and simplicity of it, it'd be great to get soul running in there! :)
