### ISSUE TITLE
Windows: Couldn't find or load SOUL_PatchLoader.dll

### ISSUE THREAD

**Issue by LibroLibri** [soul-lang/SOUL#64]
I downloaded the Source Code, opened the JUCE (latest version is installed) project in tools/plugin and compiled it in VST3 format. I also downloaded the binaries and placed SOUL_PatchLoader.dll in my plugin folder.

When I loaded the plugin in Studio One I got a message saying that the .dll file couldn't be found or loaded. I tried placing the dll in the other location specified in Patch_Plugin_README.md and I got the same problem again.

Thinking it was the DAW's problem, I compiled the plugin as Standalone and placed the dll in the same folder as the .exe file, but I got the same error again.

**Comment by julianstorer** [comment]
OK, well you can see exactly what folders are used for locating the file here:

https://github.com/soul-lang/SOUL/blob/2f8f74e8efae005e6f1e6d5f4f11b5ae22104143/include/soul/patch/helper_classes/soul_patch_LoaderPlugin.h#L436

So you can step through that to debug it and look at the exact paths if you need to, and you can also customise it if you need to build a plugin that looks in some other specific location.
