### ISSUE TITLE
Example of distortion

### ISSUE THREAD

**Issue by robsonolivesa** [soul-lang/SOUL#7]
hello everyone, do you have a example of distortion? I have interest in develop a distortion for electric guitar.

Thank you

**Comment by cesaref** [comment]
That sounds like a great idea. If you look in the examples, there is a DiodeClipper which is a circuit simulation that models diodes to introduce distortion, and this works really nicely with guitar, so give that a go.

The other bits we've got in the examples which might be of interest are a compressor, phaser and a reverb. For a nice guitar effects chain, I think we're missing a noise gate, but apart from that, you should be able to put something great together.

If you want help with this, create a topic on the juce forum and we'll follow this up with you there.
